import { GameConfig } from "@/types";

export const GAMES: GameConfig[] = [
  {
    id: "who-said-it",
    title: "Who Said It?",
    subtitle: "Nima or Saba?",
    emoji: "💬",
    description: "Swipe right for Nima, left for Saba. Can you tell who said what?",
    pointsPerCorrect: 10,
    route: "/game/who-said-it",
    status: "locked",
    order: 1,
  },
  {
    id: "trivia",
    title: "How Well Do You Know Them?",
    subtitle: "Test your knowledge",
    emoji: "🧠",
    description: "Baby photos, first dates, and embarrassing stories. How much do you really know?",
    pointsPerCorrect: 10,
    route: "/game/trivia",
    status: "locked",
    order: 2,
  },
  {
    id: "timeline",
    title: "Love Story Timeline",
    subtitle: "Put it in order",
    emoji: "📅",
    description: "Drag their milestones into the right order. First date, first trip, the proposal...",
    pointsPerCorrect: 15,
    route: "/game/timeline",
    status: "locked",
    order: 3,
  },
  {
    id: "predictions",
    title: "Predict the Night",
    subtitle: "Over / Under",
    emoji: "🎲",
    description: "Place your bets on what happens tonight. Will the best man cry? Over/under on speech length?",
    pointsPerCorrect: 15,
    route: "/game/predictions",
    status: "locked",
    order: 4,
  },
  {
    id: "finish-sentence",
    title: "Finish Their Sentence",
    subtitle: "What did they say?",
    emoji: "🎬",
    description: "Watch the video, guess how they finished the sentence, then see the real answer.",
    pointsPerCorrect: 20,
    route: "/game/finish-sentence",
    status: "locked",
    order: 5,
  },
  {
    id: "shoe-game",
    title: "Shoe Game LIVE",
    subtitle: "Predict in real-time",
    emoji: "👠",
    description: "The couple plays on stage — you predict each answer on your phone before they reveal!",
    pointsPerCorrect: 10,
    route: "/game/shoe-game",
    status: "locked",
    order: 6,
  },
  {
    id: "love-letter",
    title: "Love Letter",
    subtitle: "Time capsule",
    emoji: "💌",
    description: "Write a message, prediction, or wish. They'll open it on their anniversary.",
    pointsPerCorrect: 0,
    route: "/game/love-letter",
    status: "locked",
    order: 7,
  },
];

export const COUPLE = {
  person1: { name: "Nima", emoji: "🤵" },
  person2: { name: "Saba", emoji: "👰" },
  hashtag: "#NimaAndSaba",
  weddingDate: "2026", // Update with actual date
} as const;
